<?php

namespace App\Commands;

use CodeIgniter\CLI\BaseCommand;
use CodeIgniter\CLI\CLI;

/**
 * Remove application data left over from development and the retired v1 demo.
 *
 * Defaults to a dry run. Pass --force to delete.
 *
 *   php spark db:prune
 *   php spark db:prune --force
 *
 * Schema and migration history are never touched.
 */
class DbPrune extends BaseCommand
{
    protected $group       = 'Database';
    protected $name        = 'db:prune';
    protected $description = 'Delete stale identities, messages and pairing records. Dry run unless --force.';
    protected $usage       = 'db:prune [--force] [--all]';

    public function run(array $params)
    {
        $db    = \Config\Database::connect();
        $force = CLI::getOption('force');
        $all   = CLI::getOption('all');

        // Everything currently stored predates the assigned-id protocol or was
        // produced by the test suites, so the default sweep is total. --all is
        // kept as an explicit alias for that intent.
        $plan = [];

        $plan['v1 messages (protocol removed — unreadable)'] =
            "DELETE FROM messages WHERE api_version <> 2";

        $plan['messages addressed to a nonexistent identity'] =
            "DELETE m FROM messages m LEFT JOIN identities i ON i.external_id = m.recipient_id WHERE i.id IS NULL";

        $plan['expired rendezvous claims'] =
            "DELETE FROM rendezvous WHERE expires_at < NOW()";

        $plan['idempotency keys past their 24h retention'] =
            "DELETE FROM idempotency_keys WHERE created_at < DATE_SUB(NOW(), INTERVAL 24 HOUR)";

        $plan['revoked/expired api tokens'] =
            "DELETE FROM api_tokens WHERE is_active = 0";

        if ($all) {
            // Legacy identities carry names no client can register any more,
            // and their messages were v1. Nothing can address or read them.
            $plan['legacy identities (client-chosen names, pre-assignment)'] =
                "DELETE FROM identities WHERE external_id NOT LIKE 'sc-%'";

            $plan['test-suite identities (assigned, but generated by tests)'] =
                "DELETE FROM identities WHERE external_id LIKE 'sc-%'";

            $plan['messages orphaned by the identity deletes'] =
                "DELETE m FROM messages m LEFT JOIN identities i ON i.external_id = m.recipient_id WHERE i.id IS NULL";

            $plan['all topics'] = "DELETE FROM topic_members";
            $plan['all topic rows'] = "DELETE FROM topics";
            $plan['all rendezvous claims'] = "DELETE FROM rendezvous";
            $plan['all idempotency keys'] = "DELETE FROM idempotency_keys";
        }

        CLI::write($force ? 'Pruning:' : 'DRY RUN — nothing will be deleted. Re-run with --force.', $force ? 'yellow' : 'green');
        CLI::newLine();

        $total = 0;
        foreach ($plan as $label => $sql) {
            $count = $this->countFor($db, $sql);

            if ($force) {
                $db->query($sql);
                $affected = $db->affectedRows();
                CLI::write(sprintf('  %-58s %6d deleted', $label, $affected));
                $total += $affected;
            } else {
                CLI::write(sprintf('  %-58s %6d would go', $label, $count));
                $total += $count;
            }
        }

        CLI::newLine();
        CLI::write($force ? "Deleted {$total} rows." : "Would delete {$total} rows.",
                   $force ? 'green' : 'white');

        if ($force) {
            CLI::newLine();
            CLI::write('Remaining:');
            foreach (['identities','api_tokens','messages','idempotency_keys','topics','topic_members','rendezvous'] as $t) {
                CLI::write(sprintf('  %-20s %d', $t, $db->query("SELECT COUNT(*) c FROM `$t`")->getRowArray()['c']));
            }
        }

        return 0;
    }

    /**
     * Row count a DELETE would affect, by rewriting it as a COUNT.
     */
    private function countFor($db, string $sql): int
    {
        if (preg_match('/^DELETE m FROM (.+)$/is', $sql, $m)) {
            $q = "SELECT COUNT(*) c FROM " . $m[1];
        } elseif (preg_match('/^DELETE FROM (\w+)(.*)$/is', $sql, $m)) {
            $q = "SELECT COUNT(*) c FROM `{$m[1]}`" . $m[2];
        } else {
            return 0;
        }

        return (int) ($db->query($q)->getRowArray()['c'] ?? 0);
    }
}
